stages:
  - test

variables:
  ANSIBLE_LOCAL_PATH: /home/gitlab-runner/builds/zvN3A5z1/0/dualedu/2022-2023/sis/dmajoros/ansible

before_script:
  - yum update -y
  - yum install -y ansible
  #- cat "$ANSIBLE_LOCAL_PATH/hosts"
  #- sudo chmod 777 "$ANSIBLE_LOCAL_PATH/hosts"

ping_nodes:
  stage: test
  tags: 
    - david-shell
  image: registry.gitlab.com/torese/docker-ansible
  script:
    - export ANSIBLE_CONFIG="$ANSIBLE_LOCAL_PATH/ansible.cfg"
    - export ANSIBLE_HOSTS="$ANSIBLE_LOCAL_PATH/hosts"
    - ansible --version
    - ansible all_nodes -i "$ANSIBLE_LOCAL_PATH/hosts" -m ping
  
