---
- name: K3S on master nodes
  hosts: masters
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: K3S installation on initial master node
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
              --token {{ k3s_token }} \
              --node-taint CriticalAddonsOnly=true:NoExecute \
              --cluster-init \
              --write-kubeconfig-mode "0644" \
              --disable servicelb 
        sed -i -e 's/127.0.0.1/{{ k3s_server_IP }}/g' /etc/rancher/k3s/k3s.yaml
      when: "'master1' in group_names"
      
    - name: K3S installation and join cluster on master nodes
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
              --token {{ k3s_token }} \
              --server https://{{ k3s_server_IP }}:6443 \
              --node-taint CriticalAddonsOnly=true:NoExecute 
      when: "'master_slaves' in group_names"

- name: K3S on worker nodes
  hosts: workers
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: K3S installation and join cluster on worker nodes
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - agent --server https://{{ k3s_server_IP }}:6443











    

