---
- name: Vypnutie firewalld a swapu
  hosts: all_nodes
  become: yes
  tasks:
    - name: Vypnutie firewalld pomocou systemctl
      command: systemctl disable firewalld --now

    - name: Zistenie stavu swapu
      shell: swapon -s
      register: swap_status
      ignore_errors: yes

    - name: Vypnutie swapu
      command: swapoff /dev/mapper/centos-swap
      when: "'/dev/mapper/centos-swap' in swap_status.stdout"
