---
- name: Vypnutie firewalld a swapu
  hosts: all_nodes
  become: yes
  tasks:
    - name: Vypnutie firewalld pomocou systemctl
      command: systemctl disable firewalld --now

    - name: Vypnutie swapu
      command: swapoff /dev/mapper/
