---
- name: K3s cleanup 
  hosts: all_nodes
  become: yes
  tasks:
    - name: K3s cleanup on master nodes
      shell: |
        /usr/local/bin/k3s-killall.sh
        /usr/local/bin/k3s-uninstall.sh
      args:
        removes: /usr/local/bin/k3s
        warn: false
      when: "'master_main' in group_names or 'master_slave' in group_names" 

    - name: K3s cleanup on worker nodes
      shell: |
        /usr/local/bin/k3s-killall.sh
        /usr/local/bin/k3s-agent-uninstall.sh
      args:
        removes: /usr/local/bin/k3s
        warn: false
      when: "'worker' in group_names"
