---
- name: K3S installation and join cluster 
  hosts: all_nodes
  become: yes

  vars:
    k3s_server_IP: "10.207.0.143"
    k3s_token: "dual-edu-token"

  tasks:
    - name: Install k3s on master node
      set_fact:
        script_content: |
          #!/bin/bash
          echo "Váš obsah skriptu sem"
          echo "Môžete pridať ďalšie príkazy"
          echo "napríklad aj k3s-install"
          k3s-install

    - name: Pridať obsah do súboru a nastaviť oprávnenia
      ansible.builtin.copy:
        content: "{{ script_content }}"
        dest: /root/k3s-installll.sh  # Nahraďte "/path/to/your/script.sh" cestou k vášmu súboru
        mode: '0755'  # Nastaví spustiteľné oprávnenia
      
