---
- name: K3s cleanup 
  hosts: all_nodes
  become: yes
  tasks:
    - name: Clone a gitlab repository
      git:
        repo: https://gitlab.dual.edu/dualedu/2022-2023/sis/dmajoros/ansible.git
        dest: /tmp
        clone: yes

