---
- name: K3s cleanup 

  hosts: all_nodes
  become: yes

  tasks:
    - name: Cleanup k3s on master node
      shell: |
        /usr/local/bin/k3s-killall.sh
        /usr/local/bin/k3s-uninstall.sh
      when: "'master' in group_names and ansible_local['k3s_installed']|default(false)"

    - name: Cleanup k3s on worker nodes
      shell: |
        /usr/local/bin/k3s-killall.sh
        /usr/local/bin/k3s-agent-uninstall.sh
      when: "'worker' in group_names and ansible_local['k3s_installed']|default(false)"